# Common
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  config:
    import: 'file:config/env.yml'

---
# local
spring:
  config:
    import: 'file:config/local.yml'
    activate:
      on-profile: local

---
# production
spring:
  config:
    import: 'file:config/prod.yml'
    activate:
      on-profile: prod